#!/bin/bash

set -e
set -v

# Copy platform to platform root.
cp -R $WORKSPACE $PLATFORM_ROOT

# Save platform with provision.
drush provision-save "$PLATFORM_ALIAS" \
  --context_type=platform \
  --root="$PLATFORM_WEB"

# Save site with provision.
drush provision-save "$SITE_ALIAS" \
  --context_type=site \
  --db_server="server_localhost" \
  --uri="$SITE_URI" \
  --platform="$PLATFORM_ALIAS" \
  --profile="$PROFILE"

# Install site with provision.
drush "$SITE_ALIAS" provision-install -v

# There is a database to import.
if [ "${USE_DATABASE}" != "false" ] && [ -f "/mnt/database/${USE_DATABASE}" ]; then
  drush "${SITE_ALIAS}" sql-drop -y
  drush "${SITE_ALIAS}" sql-cli < "/mnt/database/${USE_DATABASE}"

  drush "${SITE_ALIAS}" updb -y
fi

# Stage file proxy.
if [ "${ORIGIN_URL}" != "false" ]; then
  drush "$SITE_ALIAS" dl stage_file_proxy --dev

  drush "$SITE_ALIAS" vset stage_file_proxy_origin "${ORIGIN_URL}" -y

  if [ "${ORIGIN_DIR}" != "false" ]; then
    drush "$SITE_ALIAS" vset stage_file_proxy_origin_dir "${ORIGIN_DIR}" -y
  fi

  drush "$SITE_ALIAS" en stage_file_proxy -y
fi

# Shield
if [ "${SHIELD_USER}" != "false" ] && [ "${SHIELD_PASS}" != "false" ]; then
  drush "$SITE_ALIAS" dl shield --dev

  drush "$SITE_ALIAS" vset shield_user "${SHIELD_USER}" -y
  drush "$SITE_ALIAS" vset shield_pass "${SHIELD_PASS}" -y

  drush "$SITE_ALIAS" en shield -y
fi

# Get admin account.
ADMIN_ACCOUNT=$(drush "$SITE_ALIAS" uinf 1 | awk '/User name/{print $4}')

# Change admin password.
drush "$SITE_ALIAS" upwd "${ADMIN_ACCOUNT:-admin}" --password=nimda

# Verify platform.
drush "$PLATFORM_ALIAS" provision-verify -v
