#!/bin/bash

set -e
set -v

# Protect sites folder.
mv $PLATFORM_ROOT_LAST_INSTALL/web/sites $PLATFORM_ROOT_LAST_INSTALL/

# Replace platform code of last installation.
rm -rf $PLATFORM_ROOT_LAST_INSTALL/web
cp -R $WORKSPACE/web $PLATFORM_ROOT_LAST_INSTALL/web

# Put protected sites folder back.
rm -rf $PLATFORM_ROOT_LAST_INSTALL/web/sites
mv $PLATFORM_ROOT_LAST_INSTALL/sites $PLATFORM_ROOT_LAST_INSTALL/web/sites

# Empty all caches.
drush "${SITE_LAST_INSTALL}" cc all

# Update database.
drush "${SITE_LAST_INSTALL}" updb -y
