#!/bin/bash

set -e
set -v

# Optional set site alias without big-cheese-init.
if [ -n $1 ]; then
  SITE_ALIAS=$1
fi

SITE_PATH=$(drush site-alias ${SITE_ALIAS} --component=site_path --strict=0 2> /dev/null)

echo "SITE_ALIAS: ${SITE_ALIAS}"
echo "SITE_PATH: ${SITE_PATH}"

# Files folder
chown -R aegir:www-data "${SITE_PATH}/files"
chmod -R 775 "${SITE_PATH}/files"

# Privat folder
chown -R aegir:www-data "${SITE_PATH}/private"
chmod -R 775 "${SITE_PATH}/private"
