#!/bin/bash

set -e
set -v

# Copy platform to platform root.
cp -R $WORKSPACE $PLATFORM_ROOT

# Save platform with provision.
drush provision-save "${PLATFORM_ALIAS}" \
  --context_type=platform \
  --root="${PLATFORM_WEB}"

# Save site with provision.
drush provision-save "${SITE_ALIAS}" \
  --context_type=site \
  --db_server="server_localhost" \
  --uri="${SITE_URI}" \
  --platform="${PLATFORM_ALIAS}" \
  --profile="${PROFILE}"


# Clone site with provision.
drush @${SITE_LAST} provision-clone "${SITE_ALIAS}" "${PLATFORM_ALIAS}"

# Remove old current site alias.
if [ -n "${SITE_LAST}" ]; then

  # Remove old 'current' alias to site.
  drush "${SITE_LAST}" provision-save \
    --aliases=","

  # Verify to remove alias from vhost.
  drush "${SITE_LAST}" provision-verify
fi

# Add 'current' alias to site.
 drush "${SITE_ALIAS}" provision-save \
   --aliases="${SITE_CURRENT}" \
   --redirection=true

drush "${SITE_ALIAS}" provision-verify

# Save alias to current.
echo "${SITE_ALIAS}" > ~/.big-cheese/"${SITE_CURRENT}"

# Verify platform.
drush "$PLATFORM_ALIAS" provision-verify -v
