#!/bin/bash


# Create big-cheese home.
test -d ~/.big-cheese || mkdir -p ~/.big-cheese


# Bail if there is no .ciconfig file.
test -f .ciconfig || return 1


# Help function to read .ciconfig file.
_read() { local c=$(cat .ciconfig 2> /dev/null | grep '^\s*'$1'\s=') && echo ${c#*=} || echo ${2:-''}; }


# Variables.
NAME=$(_read name ${JOB_NAME#*-})
PROFILE=$(_read profile ${JOB_NAME#*-})
ROOT=$(_read root 'web')

USE_DATABASE=$(_read database false)

ORIGIN_URL=$(_read origin_url false)
ORIGIN_DIR=$(_read origin_dir false)

SHIELD_USER=$(_read shield_user false)
SHIELD_PASS=$(_read shield_pass false)

PLATFORM_NAME=${NAME}-build${BUILD_NUMBER}
PLATFORM_ROOT=${JENKINS_HOME}/platforms/${PLATFORM_NAME}
PLATFORM_WEB=${PLATFORM_ROOT}/${ROOT}
PLATFORM_ALIAS=@platform_$(echo $PLATFORM_NAME | sed 's/[\.-]//g')

SITE_URI=$(echo "${PLATFORM_NAME}.osborn.wunderkraut.com" | tr '[:upper:]' '[:lower:]')
SITE_CURRENT=$(echo "${NAME}-current.osborn.wunderkraut.com" | tr '[:upper:]' '[:lower:]')
SITE_ALIAS=@$(echo $SITE_URI | sed 's/[\.-]//g')

# Make sure there is a jenkins folder.
mkdir -p jenkins


# Save variables as properties.
tee jenkins/properties <<EOF
NAME = $NAME
PROFILE = $PROFILE

USE_DATABASE = $USE_DATABASE

ORIGIN_URL = $ORIGIN_URL
ORIGIN_DIR = $ORIGIN_DIR

SHIELD_USER = $SHIELD_USER
SHIELD_PASS = $SHIELD_PASS

PLATFORM_NAME = $PLATFORM_NAME
PLATFORM_ROOT = $PLATFORM_ROOT
PLATFORM_WEB = $PLATFORM_WEB
PLATFORM_ALIAS = $PLATFORM_ALIAS

SITE_URI = $SITE_URI
SITE_CURRENT = $SITE_CURRENT
SITE_ALIAS = $SITE_ALIAS
EOF
