#!/bin/bash

set -e
set -v

MEGA_QUICK_PLATFORM_ALIAS="${1}"

echo "MEGA_QUICK_PLATFORM_ALIAS: ${MEGA_QUICK_PLATFORM_ALIAS}"

# Find all site aliases on source platform.
SITES=$(big-cheese-find-site  --search-parameter="platform" --search-term="${MEGA_QUICK_PLATFORM_ALIAS}")
if [ -z "${SITES}" ]; then
  echo "No sites found on platform: ${MEGA_QUICK_PLATFORM_ALIAS}. EXIT!"
  exit 1
fi
echo "Sites found on platform ${MEGA_QUICK_PLATFORM_ALIAS}:"
echo "${SITES}"

MEGA_QUICK_DRUPAL_ROOT=$(drush site-alias ${MEGA_QUICK_PLATFORM_ALIAS} --component=root --strict=0 2> /dev/null)
MEGA_QUICK_BUILD_PATH=${MEGA_QUICK_DRUPAL_ROOT%/$ROOT}
MEGA_QUICK_BACKUP_PATH="${AEGIR_HOME}/backups/${MEGA_QUICK_JOB_NAME}-${BUILD_NUMBER_QUICK_BACKUP}"

# Set all sites in maintenance mode.
for site in ${SITES} ; do
  if [ -n "${site}" ]; then
    drush  "${site}" vset maintenance_mode -y 1
  fi
done

# Temporary move sites folder.
mv "${MEGA_QUICK_BUILD_PATH}/${ROOT}/sites" "${MEGA_QUICK_BACKUP_PATH}/"

# Revert code from quick deploy.
rm -rf "${MEGA_QUICK_BUILD_PATH}/${ROOT}"
mkdir -p "${MEGA_QUICK_BUILD_PATH}/${ROOT}"
rsync -a "${MEGA_QUICK_BACKUP_PATH}/${ROOT}/" "${MEGA_QUICK_BUILD_PATH}/${ROOT}"

# Put sites folder back.
mv "${MEGA_QUICK_BACKUP_PATH}/sites" "${MEGA_QUICK_BUILD_PATH}/${ROOT}/"

# Verify platform to deploy new code (to remote servers).
drush  "${MEGA_QUICK_PLATFORM_ALIAS}" provision-verify -v

# Restore databases.
for site in ${SITES} ; do
  if [ -n "${site}" ]; then
    BACKUP_FILE_PREFIX=$(echo "${site}" | sed 's/\@//g')
    drush "${site}" sql-drop -y
    drush "${site}" sql-cli < "${MEGA_QUICK_BACKUP_PATH}/${BACKUP_FILE_PREFIX}-dump.sql"
    drush  "${site}" cc all
    drush  "${site}" vset maintenance_mode -y 0
  fi
done
