#!/bin/bash

set -e
set -v

SITE_PATH=$(drush site-alias ${SITE_ALIAS} --component=site_path --strict=0 2> /dev/null)

# Files folder
chown -R aegir:www-data "${SITE_PATH}/files"
chmod -R 775 "${SITE_PATH}/files"

# Privat folder
chown -R aegir:www-data "${SITE_PATH}/private"
chmod -R 775 "${SITE_PATH}/private"
